### ISSUE TITLE
Binaries in release doesn't work

### ISSUE THREAD

**Issue by DanniSec** [Seraphim-Solutions/bettercinema#25]
Both Windows and Linux binaries are not working for some reason. 
o:
```
 Traceback (most recent call last):
  File "app.py", line 21, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "handlers\trakt_handler.py", line 3, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "handlers\trakt\oauth.py", line 5, in <module>
ModuleNotFoundError: No module named 'db_handler'
[12028] Failed to execute script app
```

The problem is with the `db_handler` module, which has not been changed since v1.0.0.

Running `python app.py` in the source works correctly. 
Building it manually exits with the same problem. 

My guess is this has something to do with pyinstaller, or I'm just missing something.

**Until resolved please run BetterCinema from the source**

**Comment by DanniSec** [comment]
Issue resolved in [cd29817](https://github.com/Seraphim-Solutions/bettercinema/commit/cd29817f89027f9830ba9ac4b3d1fa689e41833b).
